global:
  segment:              11.85     # seconds
  shift:                2         # seconds
  sample_rate:          44100     # Hz
  n_workers:            16
  prefetch_factor:      6


data_augmentation:
  augmentation_prob:          0.5
  kit_swap_augment_prob:      0.5
  doubling_augment_prob:      0.3
  pitch_shift_augment_prob:   0.3
  saturation_augment_prob:    0.3
  channel_swap_augment_prob:  0.5
  remix_augment_prob:         0.3


kick:
  training_mode:        'stft'
  F:                    2048
  T:                    512
  batch_size:           24
  learning_rate:        1e-4
  epochs:               22


snare:
  training_mode:        'stft'
  F:                    2048
  T:                    512
  batch_size:           24
  learning_rate:        1e-4
  epochs:               22


toms:
  training_mode:        'stft'
  F:                    2048
  T:                    512
  batch_size:           24
  learning_rate:        1e-4
  epochs:               22


hihat:
  training_mode:        'stft'
  F:                    2048
  T:                    512
  batch_size:           24
  learning_rate:        1e-4
  epochs:               22


cymbals:
  training_mode:        'stft'
  F:                    2048
  T:                    512
  batch_size:           24
  learning_rate:        1e-4
  epochs:               22
